version: '3.9'

services:

  mysql:
    image: mariadb:10.6.4-focal
    restart: always
    container_name: mysql
    hostname: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    expose:
      - 3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    networks: 
      - ridely

  transactions:
    depends_on:
      - mysql
    hostname: transaction 
    image: ubotter/edufi3.18-transactions:latest
    expose:
      - 9231
    ports:
      - 9231:9231
    links: 
      - mysql
    restart: always
    networks:
      - payment
    
  payment:
    depends_on:
      - mysql
    hostname: payment
    image: ubotter/edufi3.18-payment:latest
    expose:
      - 9232
    links: 
      - mysql
    restart: always
    networks:
      - payment

volumes:
  node_modules:

networks:
  payment:
    driver: bridge
  
