version: '3.9'

services:
  mysql:
    image: mariadb:10.6.4-focal
    restart: always
    container_name: mysql
    hostname: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    expose:
      - 3306
    volumes:
      - ./backend/sql/:/docker-entrypoint-initdb.d
    networks: 
      - payment

  transactions:
    depends_on:
      - mysql
    container_name: edufi3.18-transactions
    hostname: transaction 
    image: ubotter/edufi3.18-transactions:latest
    expose:
      - 9231
    ports:
      - 9231:9231
    restart: always
    networks:
      - payment
    
  payment:
    depends_on:
      - mysql
    container_name: edufi3.18-payment
    hostname: payment
    image: ubotter/edufi3.18-payment:latest
    expose:
      - 9232
    ports:
      - 9232:9232
    restart: always
    networks:
      - payment

  mockdb:
    depends_on:
      - mysql
    container_name: edufi3.18-mockdb
    hostname: mockdb
    image: ubotter/edufi3.18-mockdb:latest
    expose:
      - 9233
    ports:
      - 9233:9233
    restart: always
    networks:
      - payment
    

volumes:
  node_modules:

networks:
  payment:

  
