name: edufi3.18-cicd
on:
  push:
    branches:
      - main
jobs:
  # golinter:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         working-directory: backend/Payment

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         working-directory: backend/Transactions

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         working-directory: backend/model

  # cd:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install Dependencies
  #       run: |
  #         go get -u github.com/swaggo/swag/cmd/swag
  #         go get -u github.com/swaggo/http-swagger
  #         go get -u github.com/alecthomas/template

  #     - name: Generate swag docs
  #       run: |
  #         cd backend/Payment
  #         export PATH=$(go env GOPATH)/bin:$PATH
  #         swag init
  #         ls

  deployPaymentcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build ./Payment --tag ${{ secrets.DOCKER_USERNAME }}/edufi3.18-payment

      - name: Push to Docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/edufi3.18-payment

  deployTransactionscontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build ./Payment --tag ${{ secrets.DOCKER_USERNAME }}/edufi3.18-transactions

      - name: Push to Docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/edufi3.18-transactions
