name: edufi3.18-cicd
on:
  push:
    branches:
      - main
jobs:
  golinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: backend/Payment

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: backend/Transactions

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: backend/model

  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go get -u github.com/swaggo/swag/cmd/swag
          go get -u github.com/swaggo/http-swagger
          go get -u github.com/alecthomas/template

      - name: Generate swag docs
        run: |
          cd backend/Payment
          swag init
          ls

      # - name: adding

  deploycontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubotter/edufi3.18-payment
          tag_with_ref: true
